[workspace]
members = [
  "crates/rostra-core",
  "crates/rostra-dm",
  "crates/rostra",
  "crates/rostra-client",
  "crates/rostra-client-db",
  "crates/rostra-p2p",
  "crates/rostra-p2p-api",
  "crates/rostra-util",
  "crates/rostra-util-bind-addr",
  "crates/rostra-util-dedup-chan",
  "crates/rostra-util-error",
  "crates/rostra-util-fmt",
  "crates/rostra-web-ui",
  "crates/rostra-djot",
  "crates/axum-dpc-static-assets",
  "crates/tower-sessions-redb-store",
  "crates/bots/rostra-bot",
]
resolver = "2"

[workspace.package]
version = "0.1.3"
edition = "2024"
rust-version = "1.91"
license = "MIT OR APACHE-2.0 OR MPL-2.0"
description = "A p2p (f2f) social network."

[workspace.lints.clippy]
collapsible_if = "allow"
collapsible_else_if = "allow"
dbg_macro = "deny"
literal_string_with_formatting_args = "deny"

[workspace.metadata]
name = "rostra"
version = "0.1.3"
edition = "2021"
license = "MIT"

[workspace.dependencies]
age = { version = "=0.12.1", default-features = false }
base64 = "0.22"
x25519-dalek = "2"
zeroize = "1"
atom_syndication = "0.4"
async-stream = "0.3.6"
async-trait = "0.1"
anyhow = "1.0.95"
axum = { version = "0.8.1", features = ["macros"] }
axum-dpc-static-assets = { path = "crates/axum-dpc-static-assets" }
axum-extra = { version = "0.10.0" }
backon = "1.3.0"
bao-tree = "0.13"
bech32 = "0.11.0"
bincode = { version = "2.0.0", features = ["derive"] }
blake3 = "1.5.5"
brotli = "*"
bon = "3.3.0"
bip39 = "2.0.0"
cbor4ii = "1.0.0"
# ciborium = "0.2.2"
clap = { version = "4.5.23", features = ["derive", "env"] }
convi = { version = "0.1.1", features = ["min_target_pointer_width_32"] }
data-encoding = "2.7"
directories = "5"
divan = "0.1.18"
duct = "*"
ed25519-dalek = "3.0.0"
futures = "0.3.31"
futures-lite = "2.6.1"
infer = "0.19.0"
mime = "0.3.17"
bytes = "*"
listenfd = "1.0.2"
futures-util = "*"
iroh = { version = "1.1.0", default-features = false, features = ["tls-ring"] }
iroh-base = { version = "1.1.0", default-features = false }
iroh-io = "0.6.2"
itertools = "0.13.0"
jotup = { version = "0.10.0", features = ["async"] }
pkarr = "8.0.1"
proptest = "1.6.0"
maud = "*"
n0-future = "0.3.2"
tempfile = "3.14.0"
test-log = { version = "0.2.16", features = ["trace"] }
trybuild = "1"
rand = "0.9"
redb = "2.3.0"
redb-bincode = "0.5.0"
rostra-core = { version = "0.1.3", path = "crates/rostra-core" }
rostra-client = { path = "crates/rostra-client" }
rostra-client-db = { version = "0.1.3", path = "crates/rostra-client-db" }
rostra-dm = { version = "0.1.3", path = "crates/rostra-dm" }
rostra-p2p = { version = "0.1.3", path = "crates/rostra-p2p" }
rostra-p2p-api = { version = "0.1.3", path = "crates/rostra-p2p-api" }
rostra-util = { version = "0.1.3", path = "crates/rostra-util" }
rostra-util-bind-addr = { path = "crates/rostra-util-bind-addr" }
# rostra-util-dedup-chan = { path = "crates/rostra-util-dedup-chan" }
dedup-chan = { version = "0.1.3", path = "crates/rostra-util-dedup-chan", package = "rostra-util-dedup-chan" }
rostra-util-error = { version = "0.1.3", path = "crates/rostra-util-error" }
rostra-util-fmt = { version = "0.1.3", path = "crates/rostra-util-fmt" }
rostra-web-ui = { path = "crates/rostra-web-ui" }
rostra-djot = { version = "0.1.3", path = "crates/rostra-djot" }
serde = "1.0.216"
serde_bytes = "0.11.15"
serde_json = "1.0.134"
unicode-segmentation = "1.12.0"
url = "2.5.4"
urlencoding = "2"
snafu = { version = "0.8.5", features = ["rust_1_81"] }
time = { version = "0.3.36", features = ["formatting"] }
tokio = { version = "1.42.0", features = ["macros", "signal"] }
tokio-stream = "*"
tower = "*"
tower-cookies = "*"
tower-http = "0.5"
tower-sessions = "0.14.0"
tower-sessions-core = "0.14.0"
tower-sessions-redb-store = { path = "crates/tower-sessions-redb-store" }
tower-service = "0.3.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
z32 = "1.1.1"
reqwest = { version = "0.12", default-features = false, features = [
  "rustls-tls",
  "cookies",
] }
reqwest-13 = { package = "reqwest", version = "0.13", default-features = false, features = [
  "rustls",
] }
quick-xml = "0.41.0"
scraper = "0.20"
cssparser = "0.31"
webpki-root-certs = "1.0"


[profile.dev]
debug = "line-tables-only"
lto = "off"
incremental = true

[profile.dev.package."*"] # external dependencies
opt-level = 1

[profile.dev.package]
ring = { opt-level = 2 }
redb = { opt-level = 2 }
ed25519 = { opt-level = 2 }
ed25519-dalek = { opt-level = 2 }
brotli = { opt-level = 2 }
brotli-decompressor = { opt-level = 2 }
data-encoding = { opt-level = 2 }
tokio = { opt-level = 2 }
serde = { opt-level = 2 }
serde_derive = { opt-level = 3 }

[profile.ci]
inherits = "dev"
incremental = false

[profile.release]
# debug = "line-tables-only"
# super-slow, and we don't need so much speed
# lto = "fat"
# codegen-units = 1

# Workaround: https://github.com/rust-lang/cargo/issues/12457 which causes
#             https://github.com/ipetkov/crane/issues/370
[profile.dev.build-override]
debug = false
[profile.ci.build-override]
debug = false
[profile.release.build-override]
debug = false
