[package]
rust-version = { workspace = true }
name = "tower-sessions-redb-store"
description = "Redb session store backend for tower-sessions"
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
bincode = { workspace = true }
redb = { workspace = true }
redb-bincode = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tower-sessions-core = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
