[package]
name = "rostra-client"
description = "Integration runtime for Rostra peer-to-peer clients"
edition = { workspace = true }
rust-version = { workspace = true }
license = "MIT OR Apache-2.0 OR MPL-2.0"
version = { workspace = true }
repository = "https://github.com/dpc/rostra"
homepage = "https://rostra.me"
documentation = "https://docs.rs/rostra-client"
readme = "README.md"
keywords = ["rostra", "p2p", "client", "social-network"]
categories = ["asynchronous", "network-programming"]
include = [
  "Cargo.toml",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "LICENSE-MPL",
  "examples/**",
  "src/**",
  "tests/**",
]

[lints]
workspace = true

[dependencies]
rostra-dm = { workspace = true }
anyhow = { workspace = true }
backon = { workspace = true }
bincode = { workspace = true }
convi = { workspace = true }
bon = { workspace = true }
data-encoding = { workspace = true }
ed25519-dalek = { workspace = true }
futures = { workspace = true }
futures-lite = { workspace = true }
iroh-base = { workspace = true }
iroh = { workspace = true }
iroh-io = { workspace = true }
itertools = { workspace = true }
n0-future = { workspace = true }
pkarr = { workspace = true, features = ["dht", "relays"] }
redb = { workspace = true }
reqwest-13 = { workspace = true }
rostra-client-db = { workspace = true }
rostra-p2p = { workspace = true }
rostra-p2p-api = { workspace = true }
rostra-core = { workspace = true, features = [
  "ed25519-dalek",
  "pkarr",
  "bincode",
  "serde",
  "rand",
] }
rostra-util-error = { workspace = true }
dedup-chan = { workspace = true }
rostra-util-fmt = { workspace = true }
rostra-util = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
rand = { workspace = true }
url = { workspace = true }
z32 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
webpki-root-certs = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
test-log = { workspace = true, features = ["trace"] }
