[package]
name = "rostra-client-db"
description = "Embedded database and projections for a Rostra client"
edition = { workspace = true }
rust-version = { workspace = true }
license = "MIT OR Apache-2.0 OR MPL-2.0"
version = { workspace = true }
repository = "https://github.com/dpc/rostra"
homepage = "https://rostra.me"
documentation = "https://docs.rs/rostra-client-db"
readme = "README.md"
keywords = ["rostra", "p2p", "database", "event"]
categories = ["database"]
include = [
  "Cargo.toml",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "LICENSE-MPL",
  "docs/**",
  "proptest-regressions/**",
  "src/**",
  "tests/**",
]

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
backon = { workspace = true }
bincode = { workspace = true }
convi = { workspace = true }
bon = { workspace = true }
data-encoding = { workspace = true }
ed25519-dalek = { workspace = true }
futures = { workspace = true }
iroh-base = { workspace = true }
iroh = { workspace = true }
iroh-io = { workspace = true }
itertools = { workspace = true }
redb = { workspace = true }
redb-bincode = { workspace = true }
rostra-p2p = { workspace = true }
rostra-p2p-api = { workspace = true }
rostra-core = { workspace = true, features = [
  "ed25519-dalek",
  "pkarr",
  "bincode",
  "serde",
  "rand",
] }
rostra-djot = { workspace = true }
rostra-util-error = { workspace = true }
rostra-util-fmt = { workspace = true }
dedup-chan = { workspace = true }
rostra-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
test-log = { workspace = true, features = ["trace"] }
time = { workspace = true }
trybuild = { workspace = true }
